on: [push, pull_request]
name: Test and build containers

jobs:
  build:
    name: Build containers
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build containers
        working-directory: app
        run: docker-compose up --build -d

      - name: Wait for container to be running
        run: sleep 60
        
      - name: List containers
        run: docker ps

      - name: Check minio status
        run: '[[ $(docker inspect  minio-raw --format="{{.State.Health.Status}}") == "healthy" ]] && exit 0 || exit 1'

      - name: Check elasticsearch status
        run: |
          curl -XGET 'localhost:9200/_cluster/health?pretty'

      - name: Check kibana status
        run: |
          curl -XGET 'localhost:9200/_cluster/health?pretty'




    
