on: push
name: Test and build containers

jobs:
  build:

    name: Build containers
    runs-on: Ubuntu-latest
    steps:
      - name: Flow started by ${{ github.actor }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build containers
        working-directory: app
        run: docker-compose up --build -d

      - name: Wait for container to be running
        run: sleep 60

  check-containers:
    name: Test containers healthy
    runs-on: Ubuntu-latest
    needs:
      - build
    steps:
      - name: Check minio status
        run: '[[ $(docker inspect  minio-raw --format="{{.State.Health.Status}}") == "healthy" ]] && exit 0 || exit 1'

      - name: Check elasticsearch status
        run: '[[ $(docker inspect elasticsearch --format="{{.State.Health.Status}}") == "healthy" ]] && exit 0 || exit 1'

      - name: Check kibana status
        run: '[[ $(docker inspect kibana --format="{{.State.Health.Status}}") == "healthy" ]] && exit 0 || exit 1'




    